language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t jean9116/docker-react -f Dockerfile.dev .

script_
    - docker run -e CI=true jean9116/docker-react npm run test -- --coverage